#include <iostream>
#include <locale.h>
using namespace std;

/*15)
Dada una lista de 5 números, cargarlos en un vector. Armar luego otro vector de 9 elementos donde por cada 2 elementos del vector original 
intercale el promedio de ellos. Por ejemplo: [2, 4, 6, 8, 10],  el vector queda: [2, 3, 4, 5, 6, 7, 8, 9, 10].*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}