#include <iostream>
#include <locale.h>
using namespace std;

/*17)
Dada una lista de 10 números, cargarlos en un vector. Luego detectar si en el vector hay elementos repetidos y 
generar otro vector con los elementos repetidos reemplazados por ceros.

Ejemplo Vector 1: [8, 20, 20, -7, 15, 12, 15, -5, 11, 18]
Ejemplo Vector 2: [8, 0, 0, -7, 0, 12, 0, -5, 11, 18]
*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}