#include <iostream>
#include <locale.h>
using namespace std;

/*19)
Dadas dos listas de 10 números cada una y sin números repetidos, cargarlas en dos vectores. 
Generar un tercer vector que contenga solamente aquellos elementos que están repetidos en ambos vectores. Mostrar en pantalla el nuevo vector. 

Vector 1: [8, 10, -3, 5, 7]
Vector 2: [10, -8, 5, 9, -3]
Vector 3: [10, -3, 5]
*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}