#include <iostream>
#include <locale.h>
using namespace std;

/*23)
Una empresa posee un grupo de 15 vendedores para atender a sus clientes. Por cada venta realizada se genera un registro con la siguiente información:
Número de vendedor (1 a 15)
Importe de la venta (en $)

Un vendedor puede realizar más de una venta. El último registro se indica con número de vendedor igual a 0.

Se pide determinar e informar:

a) El número de vendedor que más vendió en total (en $).
b) Cada uno de los números de vendedores que no hayan realizado ventas.
c) El total recaudado por la empresa por todas las ventas efectuadas por sus vendedores*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}