#include <iostream>
#include <locale.h>
using namespace std;

/*24)
Una empresa que fabrica 200 artículos tiene la siguiente información para cada uno de las ventas del mes anterior:

Código de Artículo (1 a 200)
Día (1 a 31)
Cantidad vendida

Puede haber más de un registro para el mismo artículo. El lote finaliza con un registro con número de artículo igual a cero. Se pide determinar e informar:

a) Informar para cada código de artículo la cantidad total vendida en el mes.
b) Informar los días en los que no hubo ventas.
c) Informar los códigos de los artículos cuyas ventas en cantidad son mayores al promedio.*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}