#include <iostream>
#include <locale.h>
using namespace std;

/*21)
Hacer un programa para ingresar las encuestas de edad efectuadas a 200 personas y luego listar la cantidad de personas en cada rango 
de edad según la siguiente tabla.

Década 0.	(Edad 1-9)	Cantidad de encuestados: 99
Década 1.	(Edad 10-19)	Cantidad de encuestados: 99
……………………………	
Década 9.	(Edad 90-99)	Cantidad de encuestados: 99*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}