#include <iostream>
#include <locale.h>
using namespace std;

/*25)
Una agencia de viajes comercializa 20 planes de turismo, para cada uno de ellos se generó un registro con los siguientes datos:

-Número de plan (1 a 20)
-Precio al contado
-Precio con tarjeta

Los precios son por persona, estos datos se ingresan desordenados.
Existe un segundo lote con las ventas efectuadas durante el mes pasado en los 8 locales de atención al público.
Por cada venta que se concretó se dispone de los siguientes datos:

-Número de local (1 a 8)
-Número de plan contratado (1 a 20)
-Cantidad de personas que viajan
-Código de pago (1= contado,2= tarjeta)

Este lote finaliza con un registro con número de local igual a 9. A partir de esta información se pide:

a) Informar el total recaudado por la empresa por pago al contado y por pago con tarjeta entre todos los locales.
b) Informar cuál fue el plan que eligieron más personas en total.*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}