#include <iostream>
#include <locale.h>
using namespace std;

/*20)
Dadas dos listas de 5 números cada una y sin números repetidos, cargarlas en dos vectores. 
Generar un tercer vector que contenga los elementos de ambos vectores intercalados. Mostrar en pantalla el nuevo vector.

Vector 1: [8, 10, -3, 5, 7]
Vector 2: [20, -8, 10, 9, 3]
Vector 3: [8, 20, 10, -8, -3, 10, 5, 9, 7, 3]
*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}