#include <iostream>
#include <locale.h>
using namespace std;

/*26)
Una empresa con varias sucursales, dispone de un primer lote de registros con la siguiente información:

-Número de artículo (1 a 25)
-Precio Unitario

Este lote se encuentra desordenado.
Dispone de un segundo lote con la información de las ventas que se efectuaron en cada una de las sucursales, con la siguiente información:

-Número de artículo (1 a 25)
-Número de sucursal (1 a 5)
-Cantidad vendida

Puede haber más de un registro para el mismo artículo y para la misma sucursal.
El último registro se indica con número de artículo igual a cero.
Se pide determinar e informar:

a) Cantidad total vendida por cada artículo.
b) Monto total recaudado por la empresa.
c) Número de sucursal que más artículos vendió en total. (sin discriminar por artículo)

*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}