#include <iostream>
#include <locale.h>
using namespace std;

/*28)
Un negocio de venta de libros cuenta con los siguientes lotes de información:

Un primer lote cuenta con los datos de los libros que este negocio vende. Cada registro contiene:
-Código de Libro (1 a 200)
-Tema (1 a 20)
-Precio

Este lote cuenta con un total de 200 registros y se ingresa desordenado.
Un segundo lote con los datos de las ventas del último mes. Cada registro contiene los siguientes datos:

-Código de Libro (1 a 200)
-Número de Vendedor (1 a 10)
-Día de la venta (1 a 31)

Puede haber varios registros para el mismo código de libro y para el mismo vendedor. Este lote finaliza con un registro con código de libro igual a cero.

Se pide determinar e informar:
a) Indicar por separado la recaudación total para cada uno de las 31 días.
b) Cuál es el número de vendedor con mayor recaudación total por ventas.
c) Cuál es el número de tema más vendido.
NO SE PUEDE UTILIZAR NINGÚN SWITCH CON MÁS DE 3 SALIDAS.
*/

int main()
{
    setlocale(LC_ALL, "Spanish");

    int numero;
    
    return 0;
}